# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
destination: ./_site
title: DEMO - Beneficiary Claims Data API
email: bc-api@googlegroups.com
description: >- # this means to ignore newlines until "baseurl:"
  Shared Savings Program ACOs can use this FHIR-based API to retrieve bulk Medicare claims data related to their assignable or prospectively assigned beneficiaries. Under construction; feedback invited.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bcda.cms.gov" # This is a kludge for HIMMS, we can fix it later as needed. the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
cssurl: /assets/css/static-main.css

global_nav:
  - title: Home
    id: home
  - title: User Guide
    id: guide
  - title: Understanding the Data
    id: data
  - title: Updates
    id: updates

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - Dockerfiles/
  - docker-compose.yml
  - node_modules/

sass:
  sass_dir: _sass
  load_paths:
    - _sass
    - node_modules
  style: compressed
