# Legacy file 2024 

version: '3'

services:
  static_site:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.static_site
    environment:
      - JEKYLL_ENV=dev
    volumes:
      - .:/bcda-site-static
