services:
  site:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:80
    develop:
      watch:
        - action: rebuild
          path: src
        - action: rebuild
          path: Gemfile
        - action: rebuild
          path: Gemfile.lock
        - action: rebuild
          path: package.json
        - action: rebuild
          path: package-lock.json
        - action: rebuild
          path: gulpfile.js

# For pa11y-ci
  pa11y-ci:
    # Reuses branch's cached image on each CI run (see a11y-check.yml)
    image: bcda-static-site-pa11y-ci
    build:
      context: .
      dockerfile: Dockerfile.pa11y
    working_dir: /app
