services:
  site:
    build: 
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - 4000:4000
    develop:
      watch:
        - action: rebuild
          path: .
          