services:
  site:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    develop:
      watch:
        - action: rebuild
          path: src
        - action: rebuild
          path: Gemfile
        - action: rebuild
          path: package.json
        - action: rebuild
          path: gulpfile.js
          