FROM jekyll/builder

ENV BUNDLE_PATH=$GEM_HOME
WORKDIR /bcda-site-static
COPY . .
RUN ["bundle", "install"]
ENTRYPOINT ["bundle", "exec", "jekyll", "build", "--config", "_config.yml,_version_config.yml"]
