name: 508 Compliance Check

on:
  schedule:
    - cron: 17 8 * * 1
  workflow_dispatch:
    inputs:
      target_host:
        description: Check where?
        required: true
        default: "https://stage.bcda.cms.gov"
        type: choice
        options:
          - "https://stage.bcda.cms.gov"
          - "https://bcda.cms.gov"

jobs:
  compliance_check:
    name: Compliance Check
    runs-on: codebuild-bcda-static-site-${{github.run_id}}-${{github.run_attempt}}
    steps:
      - name: Set Target Base
        id: target-base
        run: |
          echo "TARGET_BASE_URL=${{ inputs.target_host || 'https://stage.bcda.cms.gov' }}" >> "$GITHUB_OUTPUT"
      - name: Run Axe Check
        env:
          TARGET_BASE_URL: ${{ steps.target-base.outputs.TARGET_BASE_URL }}
        run: |
          TARGETS_TO_SCAN="${TARGET_BASE_URL}"
          TARGETS_TO_SCAN="${TARGETS_TO_SCAN} ${TARGET_BASE_URL}/guide.html"
          TARGETS_TO_SCAN="${TARGETS_TO_SCAN} ${TARGET_BASE_URL}/build.html"
          TARGETS_TO_SCAN="${TARGETS_TO_SCAN} ${TARGET_BASE_URL}/data.html"
          TARGETS_TO_SCAN="${TARGETS_TO_SCAN} ${TARGET_BASE_URL}/updates.html"
          TARGETS_TO_SCAN="${TARGETS_TO_SCAN} ${TARGET_BASE_URL}/partial.html"
          docker run --init --rm --cap-add=SYS_ADMIN orenfromberg/axe-puppeteer-ci:1.0.0@sha256:f83527a3ae8ab74088c001abfe44836946ba73f0afbbf460447f8a0c40281e70 ${TARGETS_TO_SCAN}
      - uses: slackapi/slack-github-action@v2.0.0
        name: Slack Success
        if: ${{ success() }}
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          # Sends to bcda-deploy
          payload: |
            channel: "C03S23MJFJS"
            attachments:
              - color: good
                text: "SUCCESS: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Static Site 508 Compliance>"
                mrkdown_in:
                  - text
      - uses: slackapi/slack-github-action@v2.0.0
        name: Slack failure
        if: ${{ failure() }}
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          # Sends to bcda-alerts
          payload: |
            channel: "C034CFU945C"
            attachments:
              - color: danger
                text: "FAILURE: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Static Site 508 Compliance>"
                mrkdown_in:
                  - text
