name: "Accessibility Check"

on:
  workflow_call

jobs:
  a11y-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
          # node-version: 20 ## Using a .nvmrc file to stay in sync with the repo

      # Step 3: Set base url/deployment path
      - name: Set Deployment Path
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "DEPLOY_PATH=${{ github.event.number }}" >> $GITHUB_ENV
          else
            echo "DEPLOY_PATH=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      # Step 4: Run pa11y
      - name: Run pa11y
        run: npx pa11y-ci --config pa11yci.ci.json --sitemap https://d27n86ormmec02.cloudfront.net/${{ env.DEPLOY_PATH }}/sitemap.xml --sitemap-exclude "/*.pdf"  --sitemap-find https://bcda.cms.gov/ --sitemap-replace https://d27n86ormmec02.cloudfront.net/ --json > pa11y-results.json || echo "EXIT_CODE=$?" >> $GITHUB_ENV

      # Step 5: Save pa11y summary
      - name: Save Report to Action Summary
        uses: actions/github-script@v7
        if: env.EXIT_CODE == 0 || env.EXIT_CODE == 2
        with:
          script: |
            const fs = require('fs');

            const results = "pa11y-results.json"
            const data = JSON.parse(fs.readFileSync(results, "utf-8"))

            let body = "## Accessibility Report \n\n";
            body += "| Status | URL | Errors |\n";
            body += "| ------ | --- | ------ |\n";

            Object.entries(data.results).forEach(([url, issues]) => {
              body += `${issues.length > 0 ? '❌' : '✅' } | ${url} | ${issues.length} errors |\n`;
            });

            core.summary.addRaw(body).write();

      - name: Post to Slack
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          # Sends to bcda-deploy
          payload: |
            channel: "C03S23MJFJS"
            attachments:
              - text: "Pa11y Results (/${{env.DEPLOY_PATH}}): <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Pa11y Action Summary>"
                mrkdown_in:
                  - text
