name: push to dev

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{  github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit